# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2m.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
try:
    import moviepy.editor as mpe
    from threading import Thread
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
    from PyQt5.QtGui import QIcon
    from PyQt5.QtWidgets import QDialog, QListWidget,QLineEdit , QMessageBox , QVBoxLayout, QInputDialog,QPushButton, QHBoxLayout, QApplication
except:
    os.system('pip install moviepy')
    os.system('pip install PyQt5')
finally:
    import moviepy.editor as mpe
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
    from PyQt5.QtGui import QIcon
    from PyQt5.QtWidgets import QDialog, QListWidget,QLineEdit , QMessageBox , QVBoxLayout, QInputDialog,QPushButton, QHBoxLayout, QApplication
    
class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 2)
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open.setAcceptDrops(True)
        self.open.setObjectName("open")
        self.gridLayout.addWidget(self.open, 2, 0, 1, 1)
        self.convert = QtWidgets.QPushButton(self.centralwidget)
        self.convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert.setObjectName("convert")
        self.gridLayout.addWidget(self.convert, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.open.clicked.connect(self.add_file)
        # self.convert.clicked.connect(self.convert_mp3)
        self.convert.clicked.connect(lambda:Thread(target=self.convert_mp3).start())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video to MP3"))
        self.label.setText(_translate("MainWindow", "Video to MP3 converter"))
        self.open.setText(_translate("MainWindow", "Add"))
        self.convert.setText(_translate("MainWindow", "Convert"))

    # List=[]    

    def add_file(self):
        filename = QFileDialog.getOpenFileNames()
        # global path
        # path = filename[0]
        global Listz
        Listz=filename[0]
        # print(path)
        # self.List.append(path)
        print(Listz)
        global count
        count=1
        for itemz in Listz:
            self.listWidget.addItem(str(count)+")"+str(itemz))
            count+=1
    
    def convert_mp3(self):
        self.convert.setText("Converting...")
        self.convert.setEnabled(False)
        self.open.setEnabled(False)
        for i in Listz:
            file_locn=i
            file = mpe.VideoFileClip(file_locn)
            file.audio.write_audiofile(file_locn + ".mp3")
            self.listWidget.addItem(">>> Done->"+str(file_locn)+".mp3")
        Listz.clear()
        self.convert.setText("Convert")
        self.convert.setEnabled(True)
        self.open.setEnabled(True)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
